# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-12 13:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='groza.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0456\u044f \u0440\u043e\u0431\u0456\u0442'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_data',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u043a\u0456\u043d\u0447\u0435\u043d\u043d\u044f \u0440\u043e\u0431\u0456\u0442'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_text',
            field=ckeditor.fields.RichTextField(verbose_name='\u041e\u043f\u0438\u0441 \u043e\u0431\u0454\u043a\u0442\u0443'),
        ),
    ]
