# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-12 13:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groza', '0002_auto_20170712_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='groza.Category', verbose_name='\u0411\u0430\u0442\u044c\u043a\u0456\u0432\u0441\u044c\u043a\u0438\u0439 \u043a\u043b\u0430\u0441'),
        ),
    ]
